### ISSUE TITLE
Failed to migrate db OperationalError: The server does not support SSL connections

### ISSUE THREAD

**Issue by romanvog** [Unleash/unleash-client-python#153]
latest image fails to connect to postgres

```
[2021-05-27T10:10:10.141] [ERROR] server-impl.js - Failed to migrate db OperationalError: The server does not support SSL connections
    at Socket.<anonymous> (/unleash/node_modules/pg/lib/connection.js:71:37)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  cause: Error: The server does not support SSL connections
      at Socket.<anonymous> (/unleash/node_modules/pg/lib/connection.js:71:37)
      at Object.onceWrapper (events.js:421:26)
      at Socket.emit (events.js:314:20)
      at addChunk (_stream_readable.js:297:12)
      at readableAddChunk (_stream_readable.js:272:9)
      at Socket.Readable.push (_stream_readable.js:213:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23),
  isOperational: true
```

**Comment by ivarconr** [comment]
Hi there. This issue would be better posted in [unleash repo itself](https://github.com/Unleash/unleash/issues). 

From v4. you need to explicitly set `DATABASE_SSL` to `false` if your DB is not configured to handle SSL. 
https://docs.getunleash.io/docs/deploy/getting_started#start-unleash-server
