### ISSUE TITLE
Ability to suppress logs generated by the SDK

### ISSUE THREAD

**Issue by maskarb** [Unleash/unleash-client-python#169]
**Describe the solution you'd like**
I would like the ability to suppress logs from the SDK. I have tried setting the `verbose_log_level` to the highest value, but we still see a large traceback when the Unleash server is not running or connected.

We're currently in the very early exploratory stages with incorporating Unleash. Most team members have no need to run the Unleash server while it is being developed. However, if the server is not running, we see the traceback shown below on a regular cycle (probably on the `refresh_interval`).

I do realize that it is important to log some kind of exception when the server cannot be reached, but it would be nice to have some kind of control over what is logged. I think at a minimum, it would be great if the connection error was logged as a single line with the ability to enable the traceback if desired.

**Describe alternatives you've considered**
I've considered changing the refresh interval to some arbitrarily high value, but this doesn't eliminated the logging; it just delays them.

**Additional context**
Here are example logs:
```
sources_client  | Unleash Client feature fetch failed due to exception: HTTPConnectionPool(host='unleash', port=4242): Max retries exceeded with url: /api/client/features (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cfc29bc70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
sources_client  | Traceback (most recent call last):
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
sources_client  |     conn = connection.create_connection(
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
sources_client  |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
sources_client  |   File "/usr/lib64/python3.8/socket.py", line 918, in getaddrinfo
sources_client  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
sources_client  | socket.gaierror: [Errno -2] Name or service not known
sources_client  | 
sources_client  | During handling of the above exception, another exception occurred:
sources_client  | 
sources_client  | Traceback (most recent call last):
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
sources_client  |     httplib_response = self._make_request(
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
sources_client  |     conn.request(method, url, **httplib_request_kw)
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connection.py", line 234, in request
sources_client  |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
sources_client  |   File "/usr/lib64/python3.8/http/client.py", line 1255, in request
sources_client  |     self._send_request(method, url, body, headers, encode_chunked)
sources_client  |   File "/usr/lib64/python3.8/http/client.py", line 1301, in _send_request
sources_client  |     self.endheaders(body, encode_chunked=encode_chunked)
sources_client  |   File "/usr/lib64/python3.8/http/client.py", line 1250, in endheaders
sources_client  |     self._send_output(message_body, encode_chunked=encode_chunked)
sources_client  |   File "/usr/lib64/python3.8/http/client.py", line 1010, in _send_output
sources_client  |     self.send(msg)
sources_client  |   File "/usr/lib64/python3.8/http/client.py", line 950, in send
sources_client  |     self.connect()
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connection.py", line 200, in connect
sources_client  |     conn = self._new_conn()
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
sources_client  |     raise NewConnectionError(
sources_client  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0cfc29bc70>: Failed to establish a new connection: [Errno -2] Name or service not known
sources_client  | 
sources_client  | During handling of the above exception, another exception occurred:
sources_client  | 
sources_client  | Traceback (most recent call last):
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/requests/adapters.py", line 439, in send
sources_client  |     resp = conn.urlopen(
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
sources_client  |     retries = retries.increment(
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
sources_client  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
sources_client  | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='unleash', port=4242): Max retries exceeded with url: /api/client/features (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cfc29bc70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
sources_client  | 
sources_client  | During handling of the above exception, another exception occurred:
sources_client  | 
sources_client  | Traceback (most recent call last):
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/UnleashClient/api/features.py", line 42, in get_feature_toggles
sources_client  |     resp = requests.get(base_url,
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/requests/api.py", line 76, in get
sources_client  |     return request('get', url, params=params, **kwargs)
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/requests/api.py", line 61, in request
sources_client  |     return session.request(method=method, url=url, **kwargs)
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/requests/sessions.py", line 542, in request
sources_client  |     resp = self.send(prep, **send_kwargs)
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/requests/sessions.py", line 655, in send
sources_client  |     r = adapter.send(request, **kwargs)
sources_client  |   File "/opt/app-root/lib64/python3.8/site-packages/requests/adapters.py", line 516, in send
sources_client  |     raise ConnectionError(e, request=request)
sources_client  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='unleash', port=4242): Max retries exceeded with url: /api/client/features (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cfc29bc70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
sources_client  | Unleash Client metrics submission failed due to exception: HTTPConnectionPool(host='unleash', port=4242): Max retries exceeded with url: /api/client/metrics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0cfc2b5be0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
sources_client  | Unable to get feature flag toggles, using cached provisioning.
```

**Comment by ivanklee86** [comment]
Hi!

Sorry, the last week has been busier than expected.

Would you mind sharing how you're initializing the client?  I'll take a peek and see what I can suggest/tweak. 🙂

**Comment by maskarb** [comment]
Sure!

Here is the gist:
```
strategies = {
    # All new strategies should be added here.
    "schema-strategy": SchemaStrategy
}
headers = {}
token = ENVIRONMENT.get_value("CLIENT_ACCESS_TOKEN", default=None)
if token:
    headers["Authorization"] = f"Bearer {token}"

LOG.info("Initializing Unleash Client")
UNLEASH_CLIENT = UnleashClient(
    settings.UNLEASH_URL,
    "Cost Management",
    environment=ENVIRONMENT.get_value("ENVIRONMENT", default="development"),
    custom_headers=headers,
    custom_strategies=strategies,
)
UNLEASH_CLIENT.initialize_client()
```

We would then import this `UNLEASH_CLIENT` in any file we needed it.

**Comment by povilasb** [comment]
That's the workaround I've done:
```py
import logging
from UnleashClient.utils import LOGGER as unleash_logger

unleash_logger.setLevel(logging.WARNING)
# Used by unleash.
logging.getLogger("apscheduler.scheduler").setLevel(logging.WARNING)
logging.getLogger("apscheduler.executors").setLevel(logging.WARNING)
```

I reckon `UnleashClient` could expose `UnleashClient.set_log_level()` and do the above?
